import * as wwd from "./wwd";
import * as fs from "fs";
import * as path from "path";
import {expect} from 'chai';
import {Rectangle} from "./Rectangle";

const projectDir = path.join(__dirname, "..");

function dataPath(...paths: string[]): string {
  return path.join(projectDir, "data", ...paths);
}

function toArrayBuffer(buffer: Buffer) {
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
}

function readFileBuffer(path: string) {
  const buffer = fs.readFileSync(path);
  return toArrayBuffer(buffer);
}

function readRezWorldBuffer(levelIndex: number): ArrayBuffer {
  const worldPath = dataPath("CLAW.REZ", `LEVEL${levelIndex}`, "WORLDS", "WORLD.WWD");
  return readFileBuffer(worldPath);
}

function readDataWorldBuffer(filename: string): ArrayBuffer {
  const worldPath = dataPath(filename);
  return readFileBuffer(worldPath);
}

function encode(s: string): Uint8Array {
  return new TextEncoder().encode(s);
}

function decode(s: Uint8Array): string {
  return new TextDecoder().decode(s);
}

it('reads LEVEL1.WWD', () => {
  const worldBuffer = readRezWorldBuffer(1);
  wwd.readWorld(worldBuffer);
});

it('correctly reads TEST1.WWD', () => {
  const worldBuffer = readDataWorldBuffer("TEST1.WWD");
  const actual = wwd.readWorld(worldBuffer);

  const expected = new wwd.World(
    encode("Claw - Level 1"),
    encode("Monolith Productions Inc."),
    encode("November 16, 2019"),
    encode("\\PROJ\\CLAW\\CLAW.REZ"),
    encode("\\LEVEL1\\TILES"),
    encode("\\LEVEL1\\PALETTES\\MAIN.PAL"),
    155,
    110,
    encode("\\PROJ\\CLAW\\CLAW.EXE"),
    encode("LEVEL1\\IMAGES"),
    encode("GAME\\IMAGES"),
    encode(""),
    encode(""),
    encode("LEVEL"),
    encode("GAME"),
    encode(""),
    encode(""),
    [
      new wwd.Plane(
        12, // FIXME
        encode("Background"),
        64,
        64,
        50,
        50,
        50,
        -999,
        4,
        4,
        [
          1, 2, 3, 4,
          9, 10, 11, 12,
          17, 18, 19, 20,
          25, 26, 27, 28
        ],
        [encode("BACK")],
        [], // FIXME
      ),
      new wwd.Plane(
        1, // FIXME
        encode("Action"),
        64,
        64,
        100,
        100,
        50,
        0,
        4,
        4,
        [
          12, 308, -1, -1,
          926, 401, 402, -1,
          12, 403, 404, 305,
          12, 12, 12, 12
        ],
        [encode("ACTION")],
        [
          new wwd.Object_(
            1171,
            encode(""),
            encode("BehindAniCandy"),
            encode("LEVEL_TORCHSTAND"),
            encode(""),
            182,
            107,
            1000,
            -1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ),
          new wwd.Object_(
            3024,
            encode(""),
            encode("BehindAniCandy"),
            encode("LEVEL_TORCHSTAND"),
            encode(""),
            -129,
            516,
            1000,
            -1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ),
          new wwd.Object_(
            144,
            encode(""),
            encode("Soldier"),
            encode("LEVEL_SOLDIER"),
            encode(""),
            330,
            195,
            4000,
            -1,
            0,
            0,
            0,
            0,
            0,
            0,
            33,
            0,
            0,
            0,
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              33,
              33,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            144,
            0,
            453,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ),
          new wwd.Object_(
            0,
            encode(""),
            encode("Officer"),
            encode("LEVEL_OFFICER"),
            encode(""),
            220,
            130,
            4000,
            -1,
            0,
            0,
            0,
            0,
            0,
            0,
            33,
            0,
            0,
            0,
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            110,
            0,
            408,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ),
          new wwd.Object_(
            1951,
            encode(""),
            encode("FrontCandy"),
            encode("LEVEL_SKULL"),
            encode(""),
            -80,
            585,
            5000,
            -1,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ),
          new wwd.Object_(
            2724,
            encode(""),
            encode("SmallSoundTrigger"),
            encode("GAME_SOUNDICON"),
            encode("LEVEL_TRIGGER_WDOOROPEN1"),
            -134,
            521,
            9000,
            -1,
            0,
            2,
            1,
            0,
            0,
            0,
            0,
            0,
            1,
            0,
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              892,
              4630,
              951,
              4865,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            Rectangle.fromBounds(
              0,
              0,
              0,
              0,
            ),
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
          ),
        ]
      ),
      new wwd.Plane(
        4, // FIXME
        encode("Front"),
        64,
        64,
        150,
        125,
        50,
        9000,
        4,
        4,
        [
          -1, -1, -1, -1,
          -1, -1, -1, -1,
          -1, -1, -1, -1,
          -1, -1, -1, -1,
        ],
        [encode("FRONT")],
        [],
      ),
    ],
  );

  expect(actual).to.be.deep.equal(expected);
});
