import * as wwd from "./wwd";
import * as fs from "fs";
import * as path from "path";
import {expect} from 'chai';
import {Rectangle} from "./Rectangle";

const projectDir = path.join(__dirname, "..");

function dataPath(...paths: string[]): string {
  return path.join(projectDir, "data", ...paths);
}

function toArrayBuffer(buffer: Buffer) {
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength);
}

function readFileBuffer(path: string) {
  const buffer = fs.readFileSync(path);
  return toArrayBuffer(buffer);
}

function readRezWorldBuffer(levelIndex: number): ArrayBuffer {
  const worldPath = dataPath("CLAW.REZ", `LEVEL${levelIndex}`, "WORLDS", "WORLD.WWD");
  return readFileBuffer(worldPath);
}

function readDataWorldBuffer(filename: string): ArrayBuffer {
  const worldPath = dataPath(filename);
  return readFileBuffer(worldPath);
}

function encode(s: string): Uint8Array {
  return new TextEncoder().encode(s);
}

function decode(s: Uint8Array): string {
  return new TextDecoder().decode(s);
}

it('reads LEVEL1.WWD', () => {
  const worldBuffer = readRezWorldBuffer(1);
  wwd.readWorld(worldBuffer);
});

it('correctly reads TEST1.WWD', () => {
  const worldBuffer = readDataWorldBuffer("TEST1.WWD");
  const actual = wwd.readWorld(worldBuffer);

  const expected = new wwd.World(
    encode("Claw - Level 1"),
    encode("Monolith Productions Inc."),
    encode("November 16, 2019"),
    encode("\\PROJ\\CLAW\\CLAW.REZ"),
    encode("\\LEVEL1\\TILES"),
    encode("\\LEVEL1\\PALETTES\\MAIN.PAL"),
    155,
    110,
    encode("\\PROJ\\CLAW\\CLAW.EXE"),
    encode("LEVEL1\\IMAGES"),
    encode("GAME\\IMAGES"),
    encode(""),
    encode(""),
    encode("LEVEL"),
    encode("GAME"),
    encode(""),
    encode(""),
    [
      new wwd.Plane(
        12, // FIXME
        encode("Background"),
        64,
        64,
        50,
        50,
        50,
        -999,
        4,
        4,
        [
          1, 2, 3, 4,
          9, 10, 11, 12,
          17, 18, 19, 20,
          25, 26, 27, 28
        ],
        [encode("BACK")],
        [], // FIXME
      ),
      new wwd.Plane(
        1, // FIXME
        encode("Action"),
        64,
        64,
        100,
        100,
        50,
        0,
        4,
        4,
        [
          12, 308, -1, -1,
          926, 401, 402, -1,
          12, 403, 404, 305,
          12, 12, 12, 12
        ],
        [encode("ACTION")],
        [
          {
            id: 1171,
            name: encode(""),
            logic: encode("BehindAniCandy"),
            imageSet: encode("LEVEL_TORCHSTAND"),
            animation: encode(""),
            x: 182,
            y: 107,
            z: 1000,
            i: -1,
            addFlags: 0,
            dynamicFlags: 0,
            drawFlags: 0,
            userFlags: 0,
            score: 0,
            points: 0,
            powerup: 0,
            damage: 0,
            smarts: 0,
            health: 0,
            moveRect: Rectangle.fromBounds(0, 0, 0, 0),
            hitRect: Rectangle.fromBounds(0, 0, 0, 0),
            attackRect: Rectangle.fromBounds(0, 0, 0, 0),
            clipRect: Rectangle.fromBounds(0, 0, 0, 0),
            userRect1: Rectangle.fromBounds(0, 0, 0, 0),
            userRect2: Rectangle.fromBounds(0, 0, 0, 0),
            userValue1: 0,
            userValue2: 0,
            userValue3: 0,
            userValue4: 0,
            userValue5: 0,
            userValue6: 0,
            userValue7: 0,
            userValue8: 0,
            xMin: 0,
            yMin: 0,
            xMax: 0,
            yMax: 0,
            speedX: 0,
            speedY: 0,
            xTweak: 0,
            yTweak: 0,
            counter: 0,
            speed: 0,
            width: 0,
            height: 0,
            direction: 0,
            faceDir: 0,
            timeDelay: 0,
            frameDelay: 0,
            objectType: 0,
            hitTypeFlags: 0,
            xMoveRes: 0,
            yMoveRes: 0,
          },

          {
            id: 3024,
            name: encode(""),
            logic: encode("BehindAniCandy"),
            imageSet: encode("LEVEL_TORCHSTAND"),
            animation: encode(""),
            x: -129,
            y: 516,
            z: 1000,
            i: -1,
            addFlags: 0,
            dynamicFlags: 0,
            drawFlags: 0,
            userFlags: 0,
            score: 0,
            points: 0,
            powerup: 0,
            damage: 0,
            smarts: 0,
            health: 0,
            moveRect: Rectangle.fromBounds(0, 0, 0, 0),
            hitRect: Rectangle.fromBounds(0, 0, 0, 0),
            attackRect: Rectangle.fromBounds(0, 0, 0, 0),
            clipRect: Rectangle.fromBounds(0, 0, 0, 0),
            userRect1: Rectangle.fromBounds(0, 0, 0, 0),
            userRect2: Rectangle.fromBounds(0, 0, 0, 0),
            userValue1: 0,
            userValue2: 0,
            userValue3: 0,
            userValue4: 0,
            userValue5: 0,
            userValue6: 0,
            userValue7: 0,
            userValue8: 0,
            xMin: 0,
            yMin: 0,
            xMax: 0,
            yMax: 0,
            speedX: 0,
            speedY: 0,
            xTweak: 0,
            yTweak: 0,
            counter: 0,
            speed: 0,
            width: 0,
            height: 0,
            direction: 0,
            faceDir: 0,
            timeDelay: 0,
            frameDelay: 0,
            objectType: 0,
            hitTypeFlags: 0,
            xMoveRes: 0,
            yMoveRes: 0,
          },

          {
            id: 144,
            name: encode(""),
            logic: encode("Soldier"),
            imageSet: encode("LEVEL_SOLDIER"),
            animation: encode(""),
            x: 330,
            y: 495,
            z: 1000,
            i: -1,
            addFlags: 0,
            dynamicFlags: 0,
            drawFlags: 0,
            userFlags: 0,
            score: 0,
            points: 0,
            powerup: 33,
            damage: 0,
            smarts: 0,
            health: 0,
            moveRect: Rectangle.fromBounds(0, 0, 0, 0),
            hitRect: Rectangle.fromBounds(0, 0, 0, 0),
            attackRect: Rectangle.fromBounds(0, 0, 0, 0),
            clipRect: Rectangle.fromBounds(0, 0, 0, 0),
            userRect1: Rectangle.fromBounds(0, 0, 0, 0),
            userRect2: Rectangle.fromBounds(0, 0, 0, 0),
            userValue1: 0,
            userValue2: 0,
            userValue3: 0,
            userValue4: 0,
            userValue5: 0,
            userValue6: 0,
            userValue7: 0,
            userValue8: 0,
            xMin: 0,
            yMin: 0,
            xMax: 0,
            yMax: 0,
            speedX: 0,
            speedY: 0,
            xTweak: 0,
            yTweak: 0,
            counter: 0,
            speed: 0,
            width: 0,
            height: 0,
            direction: 0,
            faceDir: 0,
            timeDelay: 0,
            frameDelay: 0,
            objectType: 0,
            hitTypeFlags: 0,
            xMoveRes: 0,
            yMoveRes: 0,
          },
          {
            id: 0,
            name: encode(""),
            logic: encode("Officer"),
            imageSet: encode("LEVEL_OFFICER"),
            animation: encode(""),
            x: 220,
            y: 130,
            z: 4000,
            i: -1,
            addFlags: 0,
            dynamicFlags: 0,
            drawFlags: 0,
            userFlags: 0,
            score: 0,
            points: 0,
            powerup: 33,
            damage: 0,
            smarts: 0,
            health: 0,
            moveRect: Rectangle.fromBounds(0, 0, 0, 0),
            hitRect: Rectangle.fromBounds(0, 0, 0, 0),
            attackRect: Rectangle.fromBounds(0, 0, 0, 0),
            clipRect: Rectangle.fromBounds(0, 0, 0, 0),
            userRect1: Rectangle.fromBounds(0, 0, 0, 0),
            userRect2: Rectangle.fromBounds(0, 0, 0, 0),
            userValue1: 0,
            userValue2: 0,
            userValue3: 0,
            userValue4: 0,
            userValue5: 0,
            userValue6: 0,
            userValue7: 0,
            userValue8: 0,
            xMin: 0,
            yMin: 0,
            xMax: 0,
            yMax: 0,
            speedX: 0,
            speedY: 0,
            xTweak: 0,
            yTweak: 0,
            counter: 0,
            speed: 0,
            width: 0,
            height: 0,
            direction: 0,
            faceDir: 0,
            timeDelay: 0,
            frameDelay: 0,
            objectType: 0,
            hitTypeFlags: 0,
            xMoveRes: 0,
            yMoveRes: 0,
          },

          {
            id: 1951,
            name: encode(""),
            logic: encode("FrontCandy"),
            imageSet: encode("LEVEL_SKULL"),
            animation: encode(""),
            x: -80,
            y: 585,
            z: 5000,
            i: -1,
            addFlags: 0,
            dynamicFlags: 0,
            drawFlags: 0,
            userFlags: 0,
            score: 0,
            points: 0,
            powerup: 33,
            damage: 0,
            smarts: 0,
            health: 0,
            moveRect: Rectangle.fromBounds(0, 0, 0, 0),
            hitRect: Rectangle.fromBounds(0, 0, 0, 0),
            attackRect: Rectangle.fromBounds(0, 0, 0, 0),
            clipRect: Rectangle.fromBounds(0, 0, 0, 0),
            userRect1: Rectangle.fromBounds(0, 0, 0, 0),
            userRect2: Rectangle.fromBounds(0, 0, 0, 0),
            userValue1: 0,
            userValue2: 0,
            userValue3: 0,
            userValue4: 0,
            userValue5: 0,
            userValue6: 0,
            userValue7: 0,
            userValue8: 0,
            xMin: 0,
            yMin: 0,
            xMax: 0,
            yMax: 0,
            speedX: 0,
            speedY: 0,
            xTweak: 0,
            yTweak: 0,
            counter: 0,
            speed: 0,
            width: 0,
            height: 0,
            direction: 0,
            faceDir: 0,
            timeDelay: 0,
            frameDelay: 0,
            objectType: 0,
            hitTypeFlags: 0,
            xMoveRes: 0,
            yMoveRes: 0,
          },


          {
            id: 2724,
            name: encode(""),
            logic: encode("SmallSoundTrigger"),
            imageSet: encode("GAME_SOUNDICON"),
            animation: encode("LEVEL_TRIGGER_WDOOROPEN1"),
            x: -134,
            y: 521,
            z: 9000,
            i: -1,
            addFlags: 0,
            dynamicFlags: 2,
            drawFlags: 1,
            userFlags: 0,
            score: 0,
            points: 0,
            powerup: 33,
            damage: 0,
            smarts: 1,
            health: 0,
            moveRect: Rectangle.fromBounds(0, 0, 0, 0),
            hitRect: Rectangle.fromBounds(0, 0, 0, 0),
            attackRect: Rectangle.fromBounds(0, 0, 0, 0),
            clipRect: Rectangle.fromBounds(0, 0, 0, 0),
            userRect1: Rectangle.fromBounds(0, 0, 0, 0),
            userRect2: Rectangle.fromBounds(0, 0, 0, 0),
            userValue1: 0,
            userValue2: 0,
            userValue3: 0,
            userValue4: 0,
            userValue5: 0,
            userValue6: 0,
            userValue7: 0,
            userValue8: 0,
            xMin: 0,
            yMin: 0,
            xMax: 0,
            yMax: 0,
            speedX: 0,
            speedY: 0,
            xTweak: 0,
            yTweak: 0,
            counter: 0,
            speed: 0,
            width: 0,
            height: 0,
            direction: 0,
            faceDir: 0,
            timeDelay: 0,
            frameDelay: 0,
            objectType: 0,
            hitTypeFlags: 0,
            xMoveRes: 0,
            yMoveRes: 0,
          },
        ]
      ),
      new wwd.Plane(
        4, // FIXME
        encode("Front"),
        64,
        64,
        150,
        125,
        50,
        9000,
        4,
        4,
        [
          -1, -1, -1, -1,
          -1, -1, -1, -1,
          -1, -1, -1, -1,
          -1, -1, -1, -1,
        ],
        [encode("FRONT")],
        [],
      ),
    ],
  );

  expect(actual).to.be.deep.equal(expected);
});
